baseURL = "https://shonin.net/"
languageCode = "ja"
title = "ç¯å°ã«å‘ã‹ã†"
theme = "PaperMod"
hasCJKLanguage = true
summaryLength = 20

[services]
  [services.googleAnalytics]
    ID = "G-RPK8WR094G"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
description = "ãƒ†ã‚­ã‚¹ãƒˆã‚µã‚¤ãƒˆ"
author = "ã‚·ãƒ§ã‚¦ãƒ‹ãƒ³"
defaultTheme = "dark"
disableThemeToggle = true
copyright = "ç¯å°ã«å‘ã‹ã†"
images = ["/images/ogp-default.png"]

[params.social]
twitter = "shonin_k"

[params.label]
text = "ç¯å°ã«å‘ã‹ã†"
icon = "/images/logo.png"
iconHeight = 30

[[params.socialIcons]]
name = "X"
url = "https://x.com/shonin_k"

[[params.socialIcons]]
name = "github"
url = "https://github.com/shonin-k"

[menu]
[[menu.main]]
name = "æ—¥è¨˜ "
url = "/posts/"
weight = 1
post = "ğŸ“”"

[[menu.main]]
name = "è¨˜äº‹ "
url = "/articles/"
weight = 2
post = "ğŸ“"

[[menu.main]]
name = "è£½ä½œ "
url = "/works/"
weight = 3
post = "ğŸ› ï¸"

[[menu.main]]
name = "æ¤œç´¢ "
url = "/search/"
weight = 4
post = "ğŸ”"